// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjektniMenadzment.Data;

#nullable disable

namespace ProjektniMenadzment.Migrations
{
    [DbContext(typeof(PMDbContext))]
    [Migration("20250807204042_AddIdentityUserToKorisnik")]
    partial class AddIdentityUserToKorisnik
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IdentityUser");
                });

            modelBuilder.Entity("ProjektniMenadzment.Models.Domain.ClanoviProjektum", b =>
                {
                    b.Property<Guid>("ProjekatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KorisnikId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Uloga")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ProjekatId", "KorisnikId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("ClanoviProjekta");
                });

            modelBuilder.Entity("ProjektniMenadzment.Models.Domain.KomentariZadatak", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime");

                    b.Property<Guid>("KorisnikId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Sadrzaj")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("ZadatakId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("ZadatakId");

                    b.ToTable("KomentariZadatak", (string)null);
                });

            modelBuilder.Entity("ProjektniMenadzment.Models.Domain.Korisnici", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Biografija")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BrojTelefona")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("Korisnici", (string)null);
                });

            modelBuilder.Entity("ProjektniMenadzment.Models.Domain.Projekti", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Budzet")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DatumPocetka")
                        .HasColumnType("datetime");

                    b.Property<Guid>("KreiraoKorisnikId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Opis")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly?>("Rok")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("ZanrId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("KreiraoKorisnikId");

                    b.HasIndex("ZanrId");

                    b.ToTable("Projekti", (string)null);
                });

            modelBuilder.Entity("ProjektniMenadzment.Models.Domain.Resursi", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Cena")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("DodeljenKorisniku")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Opis")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("ProjekatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DodeljenKorisniku");

                    b.HasIndex("ProjekatId");

                    b.ToTable("Resursi", (string)null);
                });

            modelBuilder.Entity("ProjektniMenadzment.Models.Domain.Zadaci", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("DodeljenKorisnikuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KreiraoKorisnikId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Opis")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Prioritet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ProjekatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("Rok")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DodeljenKorisnikuId");

                    b.HasIndex("KreiraoKorisnikId");

                    b.ToTable("Zadaci", (string)null);
                });

            modelBuilder.Entity("ProjektniMenadzment.Models.Domain.Zanrovi", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Zanrovi", (string)null);
                });

            modelBuilder.Entity("ProjektniMenadzment.Models.Domain.ClanoviProjektum", b =>
                {
                    b.HasOne("ProjektniMenadzment.Models.Domain.Korisnici", "Korisnik")
                        .WithMany("ClanoviProjekta")
                        .HasForeignKey("KorisnikId")
                        .IsRequired()
                        .HasConstraintName("FK_ClanoviProjekta_Korisnici");

                    b.HasOne("ProjektniMenadzment.Models.Domain.Projekti", "Projekat")
                        .WithMany("ClanoviProjekta")
                        .HasForeignKey("ProjekatId")
                        .IsRequired()
                        .HasConstraintName("FK_ClanoviProjekta_Projekti");

                    b.Navigation("Korisnik");

                    b.Navigation("Projekat");
                });

            modelBuilder.Entity("ProjektniMenadzment.Models.Domain.KomentariZadatak", b =>
                {
                    b.HasOne("ProjektniMenadzment.Models.Domain.Korisnici", "Korisnik")
                        .WithMany("KomentariZadataks")
                        .HasForeignKey("KorisnikId")
                        .IsRequired()
                        .HasConstraintName("FK_KomentariZadatak_Korisnici");

                    b.HasOne("ProjektniMenadzment.Models.Domain.Zadaci", "Zadatak")
                        .WithMany("KomentariZadataks")
                        .HasForeignKey("ZadatakId")
                        .IsRequired()
                        .HasConstraintName("FK_KomentariZadatak_Zadaci");

                    b.Navigation("Korisnik");

                    b.Navigation("Zadatak");
                });

            modelBuilder.Entity("ProjektniMenadzment.Models.Domain.Korisnici", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("ProjektniMenadzment.Models.Domain.Projekti", b =>
                {
                    b.HasOne("ProjektniMenadzment.Models.Domain.Korisnici", "KreiraoKorisnik")
                        .WithMany()
                        .HasForeignKey("KreiraoKorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjektniMenadzment.Models.Domain.Zanrovi", "Zanr")
                        .WithMany("Projektis")
                        .HasForeignKey("ZanrId")
                        .HasConstraintName("FK_Projekti_Zanrovi");

                    b.Navigation("KreiraoKorisnik");

                    b.Navigation("Zanr");
                });

            modelBuilder.Entity("ProjektniMenadzment.Models.Domain.Resursi", b =>
                {
                    b.HasOne("ProjektniMenadzment.Models.Domain.Korisnici", "DodeljenKorisnikuNavigation")
                        .WithMany("Resursis")
                        .HasForeignKey("DodeljenKorisniku")
                        .HasConstraintName("FK_Resursi_Korisnici");

                    b.HasOne("ProjektniMenadzment.Models.Domain.Projekti", "Projekat")
                        .WithMany("Resursis")
                        .HasForeignKey("ProjekatId")
                        .HasConstraintName("FK_Resursi_Projekti");

                    b.Navigation("DodeljenKorisnikuNavigation");

                    b.Navigation("Projekat");
                });

            modelBuilder.Entity("ProjektniMenadzment.Models.Domain.Zadaci", b =>
                {
                    b.HasOne("ProjektniMenadzment.Models.Domain.Korisnici", "DodeljenKorisniku")
                        .WithMany("ZadaciDodeljenKorisnikus")
                        .HasForeignKey("DodeljenKorisnikuId")
                        .HasConstraintName("FK_Zadaci_Korisnici");

                    b.HasOne("ProjektniMenadzment.Models.Domain.Korisnici", "KreiraoKorisnik")
                        .WithMany("ZadaciKreiraoKorisniks")
                        .HasForeignKey("KreiraoKorisnikId")
                        .IsRequired()
                        .HasConstraintName("FK_Zadaci_Korisnici1");

                    b.Navigation("DodeljenKorisniku");

                    b.Navigation("KreiraoKorisnik");
                });

            modelBuilder.Entity("ProjektniMenadzment.Models.Domain.Korisnici", b =>
                {
                    b.Navigation("ClanoviProjekta");

                    b.Navigation("KomentariZadataks");

                    b.Navigation("Resursis");

                    b.Navigation("ZadaciDodeljenKorisnikus");

                    b.Navigation("ZadaciKreiraoKorisniks");
                });

            modelBuilder.Entity("ProjektniMenadzment.Models.Domain.Projekti", b =>
                {
                    b.Navigation("ClanoviProjekta");

                    b.Navigation("Resursis");
                });

            modelBuilder.Entity("ProjektniMenadzment.Models.Domain.Zadaci", b =>
                {
                    b.Navigation("KomentariZadataks");
                });

            modelBuilder.Entity("ProjektniMenadzment.Models.Domain.Zanrovi", b =>
                {
                    b.Navigation("Projektis");
                });
#pragma warning restore 612, 618
        }
    }
}
