// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjektniMenadzment.Data;

#nullable disable

namespace ProjektniMenadzment.Data.Migrations.PM
{
    [DbContext(typeof(PMDbContext))]
    [Migration("20260525175134_InitialPM")]
    partial class InitialPM
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjektiZanrovi", b =>
                {
                    b.Property<Guid>("ProjekatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ZanrId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProjekatId", "ZanrId");

                    b.HasIndex("ZanrId");

                    b.ToTable("ProjektiZanrovi", (string)null);
                });

            modelBuilder.Entity("ProjektniMenadzment.Models.Domain.Buildovi", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DatumBuilda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NazivBuilda")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PatchNapomene")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("ProjekatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipBuilda")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Verzija")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Buildovi__3214EC0721128050");

                    b.HasIndex("ProjekatId");

                    b.ToTable("Buildovi", (string)null);
                });

            modelBuilder.Entity("ProjektniMenadzment.Models.Domain.ClanoviProjektum", b =>
                {
                    b.Property<Guid>("ProjekatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KorisnikId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Uloga")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ProjekatId", "KorisnikId");

                    b.HasIndex("KorisnikId");

                    b.ToTable("ClanoviProjekta");
                });

            modelBuilder.Entity("ProjektniMenadzment.Models.Domain.KomentariZadatak", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime");

                    b.Property<Guid>("KorisnikId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Sadrzaj")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("ZadatakId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("ZadatakId");

                    b.ToTable("KomentariZadatak", (string)null);
                });

            modelBuilder.Entity("ProjektniMenadzment.Models.Domain.Korisnici", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Biografija")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BrojTelefona")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdentityUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Korisnici", (string)null);
                });

            modelBuilder.Entity("ProjektniMenadzment.Models.Domain.Projekti", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Budzet")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DatumPocetka")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DatumPoslednjegBuilda")
                        .HasColumnType("datetime");

                    b.Property<string>("Engine")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FazaRazvoja")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("KreiraoKorisnikId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Opis")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Platforma")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("Rok")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VerzijaIgre")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("KreiraoKorisnikId");

                    b.ToTable("Projekti", (string)null);
                });

            modelBuilder.Entity("ProjektniMenadzment.Models.Domain.Resursi", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Cena")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("DodeljenKorisniku")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Opis")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("ProjekatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DodeljenKorisniku");

                    b.HasIndex("ProjekatId");

                    b.ToTable("Resursi", (string)null);
                });

            modelBuilder.Entity("ProjektniMenadzment.Models.Domain.Zadaci", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("DodeljenKorisnikuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KreiraoKorisnikId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Opis")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Prioritet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ProjekatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("Rok")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipZadatka")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("DodeljenKorisnikuId");

                    b.HasIndex("KreiraoKorisnikId");

                    b.HasIndex("ProjekatId");

                    b.ToTable("Zadaci", (string)null);
                });

            modelBuilder.Entity("ProjektniMenadzment.Models.Domain.Zanrovi", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Naziv" }, "UQ_Zanrovi_Naziv")
                        .IsUnique();

                    b.ToTable("Zanrovi", (string)null);
                });

            modelBuilder.Entity("ProjektiZanrovi", b =>
                {
                    b.HasOne("ProjektniMenadzment.Models.Domain.Projekti", null)
                        .WithMany()
                        .HasForeignKey("ProjekatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProjektiZanrovi_Projekti");

                    b.HasOne("ProjektniMenadzment.Models.Domain.Zanrovi", null)
                        .WithMany()
                        .HasForeignKey("ZanrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProjektiZanrovi_Zanrovi");
                });

            modelBuilder.Entity("ProjektniMenadzment.Models.Domain.Buildovi", b =>
                {
                    b.HasOne("ProjektniMenadzment.Models.Domain.Projekti", "Projekat")
                        .WithMany("Buildovis")
                        .HasForeignKey("ProjekatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Fk_Buildovi_Projekat");

                    b.Navigation("Projekat");
                });

            modelBuilder.Entity("ProjektniMenadzment.Models.Domain.ClanoviProjektum", b =>
                {
                    b.HasOne("ProjektniMenadzment.Models.Domain.Korisnici", "Korisnik")
                        .WithMany("ClanoviProjekta")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ClanoviProjekta_Korisnici");

                    b.HasOne("ProjektniMenadzment.Models.Domain.Projekti", "Projekat")
                        .WithMany("ClanoviProjekta")
                        .HasForeignKey("ProjekatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ClanoviProjekta_Projekti");

                    b.Navigation("Korisnik");

                    b.Navigation("Projekat");
                });

            modelBuilder.Entity("ProjektniMenadzment.Models.Domain.KomentariZadatak", b =>
                {
                    b.HasOne("ProjektniMenadzment.Models.Domain.Korisnici", "Korisnik")
                        .WithMany("KomentariZadataks")
                        .HasForeignKey("KorisnikId")
                        .IsRequired()
                        .HasConstraintName("FK_KomentariZadatak_Korisnici");

                    b.HasOne("ProjektniMenadzment.Models.Domain.Zadaci", "Zadatak")
                        .WithMany("KomentariZadataks")
                        .HasForeignKey("ZadatakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_KomentariZadatak_Zadaci");

                    b.Navigation("Korisnik");

                    b.Navigation("Zadatak");
                });

            modelBuilder.Entity("ProjektniMenadzment.Models.Domain.Projekti", b =>
                {
                    b.HasOne("ProjektniMenadzment.Models.Domain.Korisnici", "KreiraoKorisnik")
                        .WithMany("Projektis")
                        .HasForeignKey("KreiraoKorisnikId")
                        .IsRequired()
                        .HasConstraintName("FK_Projekti_KreiraoKorisnik");

                    b.Navigation("KreiraoKorisnik");
                });

            modelBuilder.Entity("ProjektniMenadzment.Models.Domain.Resursi", b =>
                {
                    b.HasOne("ProjektniMenadzment.Models.Domain.Korisnici", "DodeljenKorisnikuNavigation")
                        .WithMany("Resursis")
                        .HasForeignKey("DodeljenKorisniku")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Resursi_Korisnici");

                    b.HasOne("ProjektniMenadzment.Models.Domain.Projekti", "Projekat")
                        .WithMany("Resursis")
                        .HasForeignKey("ProjekatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Resursi_Projekti");

                    b.Navigation("DodeljenKorisnikuNavigation");

                    b.Navigation("Projekat");
                });

            modelBuilder.Entity("ProjektniMenadzment.Models.Domain.Zadaci", b =>
                {
                    b.HasOne("ProjektniMenadzment.Models.Domain.Korisnici", "DodeljenKorisniku")
                        .WithMany("ZadaciDodeljenKorisnikus")
                        .HasForeignKey("DodeljenKorisnikuId")
                        .HasConstraintName("FK_Zadaci_Korisnici");

                    b.HasOne("ProjektniMenadzment.Models.Domain.Korisnici", "KreiraoKorisnik")
                        .WithMany("ZadaciKreiraoKorisniks")
                        .HasForeignKey("KreiraoKorisnikId")
                        .IsRequired()
                        .HasConstraintName("FK_Zadaci_Korisnici1");

                    b.HasOne("ProjektniMenadzment.Models.Domain.Projekti", "Projekat")
                        .WithMany("Zadacis")
                        .HasForeignKey("ProjekatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Zadaci_Projekat");

                    b.Navigation("DodeljenKorisniku");

                    b.Navigation("KreiraoKorisnik");

                    b.Navigation("Projekat");
                });

            modelBuilder.Entity("ProjektniMenadzment.Models.Domain.Korisnici", b =>
                {
                    b.Navigation("ClanoviProjekta");

                    b.Navigation("KomentariZadataks");

                    b.Navigation("Projektis");

                    b.Navigation("Resursis");

                    b.Navigation("ZadaciDodeljenKorisnikus");

                    b.Navigation("ZadaciKreiraoKorisniks");
                });

            modelBuilder.Entity("ProjektniMenadzment.Models.Domain.Projekti", b =>
                {
                    b.Navigation("Buildovis");

                    b.Navigation("ClanoviProjekta");

                    b.Navigation("Resursis");

                    b.Navigation("Zadacis");
                });

            modelBuilder.Entity("ProjektniMenadzment.Models.Domain.Zadaci", b =>
                {
                    b.Navigation("KomentariZadataks");
                });
#pragma warning restore 612, 618
        }
    }
}
